name = "cloudpaste"
main = "worker.js"
compatibility_date = "2024-11-27"

workers_dev = true

[[kv_namespaces]]
binding = "PASTE_STORE"
id = "dc792a20848b4a87b1751efbc661fd1b"

[[kv_namespaces]]
binding = "UPLOAD_STATUS"
id = "98168c1fc08d4959adaa3b5ea5d09e05"

[[r2_buckets]]
bucket_name = "cloudpaste-files"
binding = "FILE_STORE"
